/**
 * このファイルは scripts/updateModelCatalog.ts が生成します。手で編集しないでください。
 * GitHub Actions の週次 cron（.github/workflows/model-catalog.yml）が ollama.com の
 * featured + 検索結果から再生成し、差分があればPRを自動作成します。
 *
 * 生成日時: 2026-08-15T07:30:56.157Z
 *
 * 日本語の説明・強み分類の上書きは src/system/modelMeta.ts に書いてください。
 */
import type { ScrapedModel } from './catalogTypes.js';

export const MODEL_CATALOG: ScrapedModel[] = [
  {
    name: "codegemma",
    description: "CodeGemma is a collection of powerful, lightweight models that can perform a variety of coding tasks like fill-in-the-middle code completion, code generation, natural language understanding, mathematical reasoning, and instruction following.",
    sizesB: [2,7],
    sizeTags: ["2b","7b"],
    capabilities: [],
    pulls: "3.1M",
    cloud: false,
  },
  {
    name: "codellama",
    description: "A large language model that can use text prompts to generate and discuss code.",
    sizesB: [7,13,34,70],
    sizeTags: ["7b","13b","34b","70b"],
    capabilities: [],
    pulls: "5.9M",
    cloud: false,
  },
  {
    name: "cogito",
    description: "Cogito v1 Preview is a family of hybrid reasoning models by Deep Cogito that outperform the best available open models of the same size, including counterparts from LLaMA, DeepSeek, and Qwen across most standard benchmarks.",
    sizesB: [3,8,14,32,70],
    sizeTags: ["3b","8b","14b","32b","70b"],
    capabilities: ["tools"],
    pulls: "2.1M",
    cloud: false,
  },
  {
    name: "cogito-2.1",
    description: "The Cogito v2.1 LLMs are instruction tuned generative models. All models are released under MIT license for commercial use.",
    sizesB: [671],
    sizeTags: ["671b"],
    capabilities: [],
    pulls: "220.4K",
    cloud: false,
  },
  {
    name: "command-a",
    description: "111 billion parameter model optimized for demanding enterprises that require fast, secure, and high-quality AI",
    sizesB: [111],
    sizeTags: ["111b"],
    capabilities: ["tools"],
    pulls: "224.2K",
    cloud: false,
  },
  {
    name: "command-r7b",
    description: "The smallest model in Cohere's R series delivers top-tier speed, efficiency, and quality to build powerful AI applications on commodity GPUs and edge devices.",
    sizesB: [7],
    sizeTags: ["7b"],
    capabilities: ["tools"],
    pulls: "293.5K",
    cloud: false,
  },
  {
    name: "deepcoder",
    description: "DeepCoder is a fully open-Source 14B coder model at O3-mini level, with a 1.5B version also available.",
    sizesB: [1.5,14],
    sizeTags: ["1.5b","14b"],
    capabilities: [],
    pulls: "941K",
    cloud: false,
  },
  {
    name: "deepseek-coder",
    description: "DeepSeek Coder is a capable coding model trained on two trillion code and natural language tokens.",
    sizesB: [1.3,6.7,33],
    sizeTags: ["1.3b","6.7b","33b"],
    capabilities: [],
    pulls: "4.5M",
    cloud: false,
  },
  {
    name: "deepseek-coder-v2",
    description: "An open-source Mixture-of-Experts code language model that achieves performance comparable to GPT4-Turbo in code-specific tasks.",
    sizesB: [16,236],
    sizeTags: ["16b","236b"],
    capabilities: [],
    pulls: "3M",
    cloud: false,
  },
  {
    name: "deepseek-r1",
    description: "DeepSeek-R1 is a family of open reasoning models with performance approaching that of leading models, such as O3 and Gemini 2.5 Pro.",
    sizesB: [1.5,7,8,14,32,70,671],
    sizeTags: ["1.5b","7b","8b","14b","32b","70b","671b"],
    capabilities: ["tools","thinking"],
    pulls: "91.4M",
    cloud: false,
  },
  {
    name: "deepseek-v2.5",
    description: "An upgraded version of DeekSeek-V2  that integrates the general and coding abilities of both DeepSeek-V2-Chat and DeepSeek-Coder-V2-Instruct.",
    sizesB: [236],
    sizeTags: ["236b"],
    capabilities: [],
    pulls: "284.9K",
    cloud: false,
  },
  {
    name: "deepseek-v4-flash",
    description: "DeepSeek-V4-Flash is a preview of the DeepSeek-V4 series, a Mixture-of-Experts model with 284B total parameters and 13B activated, built for efficient reasoning across a 1M-token context window.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["tools","thinking"],
    pulls: "365.2K",
    cloud: true,
  },
  {
    name: "deepseek-v4-pro",
    description: "DeepSeek-V4-Pro is a frontier Mixture-of-Experts model with a large context window and three reasoning modes.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["tools","thinking"],
    pulls: "328K",
    cloud: true,
  },
  {
    name: "devstral-small-2",
    description: "24B model that excels at using tools to explore codebases, editing multiple files and power software engineering agents.",
    sizesB: [24],
    sizeTags: ["24b"],
    capabilities: ["vision","tools"],
    pulls: "936.9K",
    cloud: false,
  },
  {
    name: "dolphin-mixtral",
    description: "Uncensored, 8x7b and 8x22b fine-tuned models based on the Mixtral mixture of experts models that excels at coding tasks. Created by Eric Hartford.",
    sizesB: [56,176],
    sizeTags: ["8x7b","8x22b"],
    capabilities: [],
    pulls: "1.9M",
    cloud: false,
  },
  {
    name: "dolphincoder",
    description: "A 7B and 15B uncensored variant of the Dolphin model family that excels at coding, based on StarCoder2.",
    sizesB: [7,15],
    sizeTags: ["7b","15b"],
    capabilities: [],
    pulls: "992.9K",
    cloud: false,
  },
  {
    name: "exaone-deep",
    description: "EXAONE Deep exhibits superior capabilities in various reasoning tasks including math and coding benchmarks, ranging from 2.4B to 32B parameters developed and released by LG AI Research.",
    sizesB: [2.4,7.8,32],
    sizeTags: ["2.4b","7.8b","32b"],
    capabilities: [],
    pulls: "758.5K",
    cloud: false,
  },
  {
    name: "functiongemma",
    description: "FunctionGemma is a specialized version of Google's Gemma 3 270M model fine-tuned explicitly for function calling.",
    sizesB: [0.27],
    sizeTags: ["270m"],
    capabilities: ["tools"],
    pulls: "180.6K",
    cloud: false,
  },
  {
    name: "gemma4",
    description: "Gemma 4 models are designed to deliver frontier-level performance at each size. They are well-suited for reasoning, agentic workflows, coding, and multimodal understanding.",
    sizesB: [2,4,12,26,31],
    sizeTags: ["e2b","e4b","12b","26b","31b"],
    capabilities: ["vision","tools","thinking","audio"],
    pulls: "22.3M",
    cloud: true,
  },
  {
    name: "glm-5.1",
    description: "GLM-5.1 is our next-generation flagship model for agentic engineering, with significantly stronger coding capabilities than its predecessor. It achieves state-of-the-art performance on SWE-Bench Pro and leads GLM-5 by a wide margin.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["tools","thinking"],
    pulls: "2.3M",
    cloud: true,
  },
  {
    name: "glm-5.2",
    description: "GLM-5.2 is Z.ai’s flagship model for the era of long-horizon tasks.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["tools","thinking"],
    pulls: "313.6K",
    cloud: true,
  },
  {
    name: "gpt-oss",
    description: "OpenAI’s open-weight models designed for powerful reasoning, agentic tasks, and versatile developer use cases.",
    sizesB: [20,120],
    sizeTags: ["20b","120b"],
    capabilities: ["tools","thinking"],
    pulls: "11.7M",
    cloud: true,
  },
  {
    name: "gpt-oss-safeguard",
    description: "gpt-oss-safeguard-20b and gpt-oss-safeguard-120b are safety reasoning models built-upon gpt-oss",
    sizesB: [20,120],
    sizeTags: ["20b","120b"],
    capabilities: ["tools","thinking"],
    pulls: "151K",
    cloud: false,
  },
  {
    name: "granite3.3",
    description: "IBM Granite 2B and 8B models are 128K context length language models that have been fine-tuned for improved reasoning and instruction-following capabilities.",
    sizesB: [2,8],
    sizeTags: ["2b","8b"],
    capabilities: ["tools"],
    pulls: "1.1M",
    cloud: false,
  },
  {
    name: "granite4.1",
    description: "IBM Granite Models are a family of enterprise-ready, open foundation models that support multilingual capabilities, coding, retrieval-augmented generation (RAG), tool use, and structured JSON output. Released under Apache 2.0 license.",
    sizesB: [3,8,30],
    sizeTags: ["3b","8b","30b"],
    capabilities: ["tools"],
    pulls: "338.1K",
    cloud: false,
  },
  {
    name: "kimi-k2.6",
    description: "Kimi K2.6 is an open-source, native multimodal agentic model that advances practical capabilities in long-horizon coding, coding-driven design, proactive autonomous execution, and swarm-based task orchestration.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["vision","tools","thinking"],
    pulls: "432.6K",
    cloud: true,
  },
  {
    name: "kimi-k2.7-code",
    description: "Kimi K2.7 Code is Moonshot AI's coding-focused agentic model built upon Kimi K2.6, with substantial improvements on real-world long-horizon coding tasks and roughly 30% lower thinking-token usage.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["vision","tools","thinking"],
    pulls: "215.1K",
    cloud: true,
  },
  {
    name: "kimi-k3",
    description: "Kimi K3 is an open-weight, native multimodal agentic model and our most capable model to date.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["vision","tools","thinking"],
    pulls: "36.6K",
    cloud: true,
  },
  {
    name: "lfm2",
    description: "LFM2 is a family of hybrid models designed for on-device deployment. LFM2-24B-A2B is the largest model in the family, scaling the architecture to 24 billion parameters while keeping inference efficient.",
    sizesB: [24],
    sizeTags: ["24b"],
    capabilities: ["tools"],
    pulls: "1.1M",
    cloud: false,
  },
  {
    name: "llama3.2",
    description: "Meta's Llama 3.2 goes small with 1B and 3B models.",
    sizesB: [1,3],
    sizeTags: ["1b","3b"],
    capabilities: ["tools"],
    pulls: "80.1M",
    cloud: false,
  },
  {
    name: "llama3.2-vision",
    description: "Llama 3.2 Vision is a collection of instruction-tuned image reasoning generative models in 11B and 90B sizes.",
    sizesB: [11,90],
    sizeTags: ["11b","90b"],
    capabilities: ["vision"],
    pulls: "5M",
    cloud: false,
  },
  {
    name: "llama3.3",
    description: "New state of the art 70B model. Llama 3.3 70B offers similar performance compared to the Llama 3.1 405B model.",
    sizesB: [70],
    sizeTags: ["70b"],
    capabilities: ["tools"],
    pulls: "4.1M",
    cloud: false,
  },
  {
    name: "llava-phi3",
    description: "A new small LLaVA model fine-tuned from Phi 3 Mini.",
    sizesB: [3.8],
    sizeTags: ["3.8b"],
    capabilities: ["vision"],
    pulls: "305.2K",
    cloud: false,
  },
  {
    name: "magistral",
    description: "Magistral is a small, efficient reasoning model with 24B parameters.",
    sizesB: [24],
    sizeTags: ["24b"],
    capabilities: ["tools","thinking"],
    pulls: "1.4M",
    cloud: false,
  },
  {
    name: "meditron",
    description: "Open-source medical large language model adapted from Llama 2 to the medical domain.",
    sizesB: [7,70],
    sizeTags: ["7b","70b"],
    capabilities: [],
    pulls: "818.2K",
    cloud: false,
  },
  {
    name: "minimax-m2.7",
    description: "MiniMax's M2-series model for coding, agentic workflows, and professional productivity.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["tools","thinking"],
    pulls: "2.4M",
    cloud: true,
  },
  {
    name: "minimax-m3",
    description: "MiniMax M3: Coding & Agentic Frontier. 1M context window. Native Multimodality.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["vision","tools","thinking"],
    pulls: "413.9K",
    cloud: true,
  },
  {
    name: "mistral-large",
    description: "Mistral Large 2 is Mistral's new flagship model that is significantly more capable in code generation, mathematics, and reasoning with 128k context window and support for dozens of languages.",
    sizesB: [123],
    sizeTags: ["123b"],
    capabilities: ["tools"],
    pulls: "1.3M",
    cloud: false,
  },
  {
    name: "mistral-medium-3.5",
    description: "Mistral Medium 3.5 is the first flagship model of Mistral AI that merged instruction-following, reasoning, and coding in a single set of 128B weights.",
    sizesB: [128],
    sizeTags: ["128b"],
    capabilities: ["vision","tools","thinking"],
    pulls: "327.1K",
    cloud: false,
  },
  {
    name: "mistral-small",
    description: "Mistral Small 3 sets a new benchmark in the “small” Large Language Models category below 70B.",
    sizesB: [22,24],
    sizeTags: ["22b","24b"],
    capabilities: ["tools"],
    pulls: "3.1M",
    cloud: false,
  },
  {
    name: "mistral-small3.1",
    description: "Building upon Mistral Small 3, Mistral Small 3.1 (2503) adds state-of-the-art vision understanding and enhances long context capabilities up to 128k tokens without compromising text performance.",
    sizesB: [24],
    sizeTags: ["24b"],
    capabilities: ["vision","tools"],
    pulls: "777.6K",
    cloud: false,
  },
  {
    name: "mistral-small3.2",
    description: "An update to Mistral Small that improves on function calling, instruction following, and less repetition errors.",
    sizesB: [24],
    sizeTags: ["24b"],
    capabilities: ["vision","tools"],
    pulls: "2.4M",
    cloud: false,
  },
  {
    name: "moondream",
    description: "moondream2 is a small vision language model designed to run efficiently on edge devices.",
    sizesB: [1.8],
    sizeTags: ["1.8b"],
    capabilities: ["vision"],
    pulls: "1.6M",
    cloud: false,
  },
  {
    name: "muse-glimmer",
    description: "Meta's latest open model built for always-on local agents. 30B parameters, licensed under Apache 2.0 and runs on a single GPU — tuned for tool use, long tasks, and failure recovery.",
    sizesB: [30],
    sizeTags: ["30b"],
    capabilities: ["vision","tools","thinking"],
    pulls: "85.1K",
    cloud: false,
  },
  {
    name: "nemotron-3-super",
    description: "NVIDIA Nemotron 3 Super is a 120B open MoE model activating just 12B parameters to deliver maximum compute efficiency and accuracy for complex multi-agent applications.",
    sizesB: [120],
    sizeTags: ["120b"],
    capabilities: ["tools","thinking"],
    pulls: "2.9M",
    cloud: true,
  },
  {
    name: "nemotron-3-ultra",
    description: "NVIDIA Nemotron 3 Ultra is built for high-throughput reasoning and long-running agent workflows.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["tools","thinking"],
    pulls: "48.3K",
    cloud: true,
  },
  {
    name: "nemotron-3.5-lightning",
    description: "NVIDIA Nemotron 3.5 Lightning is an open 30B mixture-of-experts (MoE) model with 3B active parameters built for always-on agents.",
    sizesB: [30],
    sizeTags: ["30b"],
    capabilities: ["tools","thinking"],
    pulls: "27.2K",
    cloud: false,
  },
  {
    name: "nemotron-cascade-2",
    description: "An open 30B MoE model from NVIDIA with 3B activated parameters that delivers strong reasoning and agentic capabilities.",
    sizesB: [30],
    sizeTags: ["30b"],
    capabilities: ["tools","thinking"],
    pulls: "141.4K",
    cloud: false,
  },
  {
    name: "nemotron-mini",
    description: "A commercial-friendly small language model by NVIDIA optimized for roleplay, RAG QA, and function calling.",
    sizesB: [4],
    sizeTags: ["4b"],
    capabilities: ["tools"],
    pulls: "699K",
    cloud: false,
  },
  {
    name: "nemotron3",
    description: "NVIDIA Nemotron 3 Nano Omni is a multimodal large language model that unifies video, audio, image, and text understanding to support enterprise-grade Q&A, summarization, transcription, and document intelligence workflows.",
    sizesB: [33],
    sizeTags: ["33b"],
    capabilities: ["vision","tools","thinking"],
    pulls: "643.2K",
    cloud: false,
  },
  {
    name: "opencoder",
    description: "OpenCoder is an open and reproducible code LLM family which includes 1.5B and 8B models, supporting chat in English and Chinese languages.",
    sizesB: [1.5,8],
    sizeTags: ["1.5b","8b"],
    capabilities: [],
    pulls: "627K",
    cloud: false,
  },
  {
    name: "openthinker",
    description: "A fully open-source family of reasoning models built using a dataset derived by distilling DeepSeek-R1.",
    sizesB: [7,32],
    sizeTags: ["7b","32b"],
    capabilities: [],
    pulls: "1.2M",
    cloud: false,
  },
  {
    name: "ornith",
    description: "A self-improving family of open-source models for agentic coding",
    sizesB: [9,35],
    sizeTags: ["9b","35b"],
    capabilities: ["tools"],
    pulls: "379.6K",
    cloud: false,
  },
  {
    name: "phi",
    description: "Phi-2: a 2.7B language model by Microsoft Research that demonstrates outstanding reasoning and language understanding capabilities.",
    sizesB: [2.7],
    sizeTags: ["2.7b"],
    capabilities: [],
    pulls: "1.5M",
    cloud: false,
  },
  {
    name: "phi4-mini",
    description: "Phi-4-mini brings significant enhancements in multilingual support, reasoning, and mathematics, and now, the long-awaited function calling feature is finally supported.",
    sizesB: [3.8],
    sizeTags: ["3.8b"],
    capabilities: ["tools"],
    pulls: "1.4M",
    cloud: false,
  },
  {
    name: "phi4-reasoning",
    description: "Phi 4 reasoning and reasoning plus are 14-billion parameter open-weight reasoning models that rival much larger models on complex reasoning tasks.",
    sizesB: [14],
    sizeTags: ["14b"],
    capabilities: [],
    pulls: "1.7M",
    cloud: false,
  },
  {
    name: "qwen2-math",
    description: "Qwen2 Math is a series of specialized math language models built upon the Qwen2 LLMs, which significantly outperforms the mathematical capabilities of open-source models and even closed-source models (e.g., GPT4o).",
    sizesB: [1.5,7,72],
    sizeTags: ["1.5b","7b","72b"],
    capabilities: [],
    pulls: "1.1M",
    cloud: false,
  },
  {
    name: "qwen2.5-coder",
    description: "The latest series of Code-Specific Qwen models, with significant improvements in code generation, code reasoning, and code fixing.",
    sizesB: [0.5,1.5,3,7,14,32],
    sizeTags: ["0.5b","1.5b","3b","7b","14b","32b"],
    capabilities: ["tools"],
    pulls: "20.3M",
    cloud: false,
  },
  {
    name: "qwen3-coder",
    description: "Alibaba's performant long context models for agentic and coding tasks.",
    sizesB: [30,480],
    sizeTags: ["30b","480b"],
    capabilities: ["tools"],
    pulls: "8.3M",
    cloud: false,
  },
  {
    name: "qwen3-coder-next",
    description: "Qwen3-Coder-Next is a coding-focused language model from Alibaba's Qwen team, optimized for agentic coding workflows and local development.",
    sizesB: [],
    sizeTags: [],
    capabilities: ["tools"],
    pulls: "2M",
    cloud: false,
  },
  {
    name: "qwen3.6",
    description: "Qwen3.6 delivers substantial upgrades in agentic coding and thinking preservation than previous Qwen models.",
    sizesB: [27,35],
    sizeTags: ["27b","35b"],
    capabilities: ["vision","tools","thinking"],
    pulls: "5.7M",
    cloud: false,
  },
  {
    name: "qwen3.8",
    description: "Qwen3.8 delivers substantial gains across coding, professional work, research, and long-horizon agentic tasks.",
    sizesB: [27],
    sizeTags: ["27b"],
    capabilities: ["vision","tools","thinking"],
    pulls: "34.3K",
    cloud: false,
  },
  {
    name: "qwq",
    description: "QwQ is the reasoning model of the Qwen series.",
    sizesB: [32],
    sizeTags: ["32b"],
    capabilities: ["tools"],
    pulls: "2.3M",
    cloud: false,
  },
  {
    name: "sailor2",
    description: "Sailor2 are multilingual language models made for South-East Asia. Available in 1B, 8B, and 20B parameter sizes.",
    sizesB: [1,8,20],
    sizeTags: ["1b","8b","20b"],
    capabilities: [],
    pulls: "406.9K",
    cloud: false,
  },
  {
    name: "smallthinker",
    description: "A new small reasoning model fine-tuned from the Qwen 2.5 3B Instruct model.",
    sizesB: [3],
    sizeTags: ["3b"],
    capabilities: [],
    pulls: "255.2K",
    cloud: false,
  },
  {
    name: "smollm",
    description: "🪐 A family of small models with 135M, 360M, and 1.7B parameters, trained on a new high-quality dataset.",
    sizesB: [0.135,0.36,1.7],
    sizeTags: ["135m","360m","1.7b"],
    capabilities: [],
    pulls: "2.1M",
    cloud: false,
  },
  {
    name: "sqlcoder",
    description: "SQLCoder is a code completion model fined-tuned on StarCoder for SQL generation tasks",
    sizesB: [7,15],
    sizeTags: ["7b","15b"],
    capabilities: [],
    pulls: "1.5M",
    cloud: false,
  },
  {
    name: "stable-beluga",
    description: "Llama 2 based model fine tuned on an Orca-style dataset. Originally called Free Willy.",
    sizesB: [7,13,70],
    sizeTags: ["7b","13b","70b"],
    capabilities: [],
    pulls: "923.5K",
    cloud: false,
  },
  {
    name: "stable-code",
    description: "Stable Code 3B is a coding model with instruct and code completion variants on par with models such as Code Llama 7B that are 2.5x larger.",
    sizesB: [3],
    sizeTags: ["3b"],
    capabilities: [],
    pulls: "1.1M",
    cloud: false,
  },
  {
    name: "stablelm-zephyr",
    description: "A lightweight chat model allowing accurate, and responsive output without requiring high-end hardware.",
    sizesB: [3],
    sizeTags: ["3b"],
    capabilities: [],
    pulls: "524.8K",
    cloud: false,
  },
  {
    name: "starcoder",
    description: "StarCoder is a code generation model trained on 80&#43; programming languages.",
    sizesB: [1,3,7,15],
    sizeTags: ["1b","3b","7b","15b"],
    capabilities: [],
    pulls: "1.2M",
    cloud: false,
  },
  {
    name: "starcoder2",
    description: "StarCoder2 is the next generation of transparently trained open code LLMs that comes in three sizes: 3B, 7B and 15B parameters.",
    sizesB: [3,7,15],
    sizeTags: ["3b","7b","15b"],
    capabilities: [],
    pulls: "2.9M",
    cloud: false,
  },
  {
    name: "yi-coder",
    description: "Yi-Coder is a series of open-source code language models that delivers state-of-the-art coding performance with fewer than 10 billion parameters.",
    sizesB: [1.5,9],
    sizeTags: ["1.5b","9b"],
    capabilities: [],
    pulls: "1M",
    cloud: false,
  },
];
